// const dummyInput = [
//     [
//         [
//             "0-0",
//             0,
//             1200,
//             1,
//             "source-over"
//         ],
//         [
//             "0-1",
//             1500,
//             600,
//             1,
//             "source-over"
//         ],
//         [
//             "0-2",
//             3000,
//             600,
//             1,
//             "source-over"
//         ]
//     ],
//     [
//         [
//             "1-0",
//             0,
//             2400,
//             1,
//             "source-over"
//         ],
//         [
//             "1-1",
//             2400,
//             4800,
//             1,
//             "source-over"
//         ],
//         [
//             "1-2",
//             7200,
//             2400,
//             1,
//             "source-over"
//         ],
//         [
//             "1-3",
//             9600,
//             1200,
//             1,
//             "source-over"
//         ]
//     ],
//     [
//         [
//             "2-0",
//             0,
//             3600,
//             1,
//             "source-over"
//         ],
//         [
//             "2-1",
//             3600,
//             2400,
//             1,
//             "source-over"
//         ],
//         [
//             "2-2",
//             6000,
//             1200,
//             1,
//             "source-over"
//         ]
//     ],
//     [
//         [
//             "3-0",
//             2400,
//             4800,
//             1,
//             "source-over"
//         ],
//         [
//             "3-1",
//             7200,
//             2400,
//             1,
//             "source-over"
//         ],
//         [
//             "3-2",
//             12000,
//             4800,
//             1,
//             "source-over"
//         ],
//         [
//             "3-3",
//             16800,
//             1800,
//             1,
//             "source-over"
//         ]
//     ]
// ]

const getFrameFromExport = (data, frame) => {
    return data.flat().filter(region => {
        return frame >= region[1] && frame < region[1] + region[2]
    }).reverse()
}